import 'tables.dart';
import 'package:drift/drift.dart';

// Generated by drift_dev when running `build_runner build`
part 'database.g.dart';

@DriftDatabase(
    include: {'tables.dart'})
class SharedDatabase extends _$SharedDatabase {
  //SharedDatabase(DatabaseConnection conn) : super.connect(conn);

  SharedDatabase(QueryExecutor e) : super(e);
  // the schemaVersion getter and the constructor from the previous page
  // have been omitted.

  // loads all todo entries
  //Future<List<Product>> get allTodoEntries => select(products).get();

  // watches all todo entries in a given category. The stream will automatically
  // emit new items whenever the underlying data changes.
  //Stream<List<Product>> watchEntriesInCategory(Category c) {
  // return (select(products)..where((t) => t.categoryID.equals(c.id))).watch();
  }
  //SharedDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;
}
